# Site Settings
title: Edgar G. Martínez-Mendoza
url: 'https://edgargmartinez.github.io/'
baseurl: 'edgargmartinez.github.io' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Edgar G. Martínez-Mendoza
tagline: Petroleum Engineer
pic: profile_egmm.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: I am currently working on my master’s thesis in the Earth Sciences Graduated Program 
at Universidad Nacional Autónoma de México, which is advised by Dr. Martin Diaz-Viera from Mexican Petroleum Institute. The purpose of my research is to use pore network models in EOR simulations.
My research purpose is to use pore network models in EOR simulations.


#sidebar links
email: edgargmartinezm@gmail.com
phone: 012 345 6789
website: edgargmartinez.github.io #do not add http://
linkedin: alandoe
github: edgargmartinez
twitter: '@webjeda'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
